pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://maven.google.com" // Google's Maven repository
        }
        maven { url "https://jitpack.io" }
    }
}
rootProject.name = "Mais Fluminense"
include ':app'
